import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import "@/lib/gsap-setup"; 

import SmoothScroll from "@/components/smooth-scroll";
import CustomCursor from "@/hooks/custom-cursor";
import Navbar from "@/components/navbar";
import ContactFloatButton from "@/components/contact-float-button"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const handleOpenContactModal = () => {
    console.log("Open Contact Modal");
  };

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning 
    >
    <body 
      className="min-h-full flex flex-col"
      suppressHydrationWarning 
    >
      <div id="scroll-cover" className="fixed inset-0 z-[9999] bg-[#030303] opacity-0 pointer-events-none transition-opacity duration-300" />
      <CustomCursor />
      
      <SmoothScroll>
        <Navbar />
        {children}
        <ContactFloatButton/>
      </SmoothScroll>
    </body>
    </html>
  );
}